# 测试配置文件

server:
  port: 8811
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/interview
    username: root
    password: admin
  # Redis 配置
  # todo 需替换配置
  data:
    redis:
      database: 1
      host: 192.168.34.100
      port: 6379
      password: admin
  # Elasticsearch 配置
  # todo 需替换配置
  elasticsearch:
    uris: http://localhost:9200
    username: root
    password: 123456